import http.server
import socketserver
from minidsp import minidsp
from urllib.parse import urlparse
from urllib.parse import parse_qs
import os

m = minidsp()

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "application/json")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # # # Extract query param
        # volume = ""
        # mute = ""
        # # source = ""
        # # query_components = parse_qs(urlparse(self.path).query)
        # # if 'name' in query_components:
        # #     name = query_components["name"][0]

        # Some custom HTML code, possibly generated by another function

        # Writing the HTML contents with UTF-8
        stream = os.popen("minidsp -o json")

        self.wfile.write(bytes(stream.read(), "utf8"))

        return

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 5004
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()